kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-database-persistent-volume
  labels:
    type: local
spec:
  storageClassName: mongo-manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
