apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: devbjoernbodk/kubernetes-worker
          env:
            - name: REDIS_HOST # Redis config
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: 6379
